services:
  database_backend:
    image: postgres:15
    container_name: database_backend_postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    volumes:
      - database_backend_data:/var/lib/postgresql/data

  redis_backend:
    image: redis:7
    container_name: redis_backend
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_backend_data:/data

volumes:
  database_backend_data:
  redis_backend_data:
