export enum PaymentMethodsName {
  AGENDAMENTO_ELETRONICO = "Agendamento Eletrônico",
  AVERBACAO = "Averbação",
  BOLETO = "Boleto",
  BOLETO_AUT = "Boleto (Aut)",
  CARTAO = "Cartão",
  CARTAO_AUT_RECORRENTE = "Cartão (Aut Recorrente)",
  CARTAO_AUT = "Cartão (Aut)",
  CARTAO_CREDITO = "Cartão de Crédito",
  CARTAO_DEBITO = "Cartão de Débito",
  CHEQUE = "Cheque",
  DEPOSITO_CONTA = "Depósito em conta",
  DESCONTO_FOLHA = "Desconto em Folha",
  DINHEIRO = "Dinheiro",
  DEBITO_CONTA = "Débito em conta",
  DEBITO_CONTA_AUT = "Débito em conta (Aut)",
  DEBITO_TELEFONE = "Débito no telefone",
  OCORRENCIAS = "Ocorrências",
  PIX = "PIX",
  PIX_AUT = "PIX (Aut)",
  PERMUTA = "Permuta",
}